<?php

namespace UserBundle\Repository;

/**
 * User_voteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_voteRepository extends \Doctrine\ORM\EntityRepository
{
}
