<?php

namespace ProductBundle\Repository;

/**
 * Note_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Note_productRepository extends \Doctrine\ORM\EntityRepository
{
}
